name: 'Run Pest PHP'
description: 'Run Pest PHP'
author: 'Emerson Carvalho'

inputs:
  php-version:
    description: 'PHP version used to run Pest'
    required: false
    default: '8.3'
  working-directory:
    description: 'Directory containing composer.json and the Laravel app'
    required: false
    default: '.'
  composer-options:
    description: 'Extra options for composer install (e.g., --no-scripts)'
    required: false
    default: ''
  node-version:
    description: 'Node version used to build assets'
    required: false
    default: '18'
  pest-args:
    description: 'Extra arguments passed to Pest (e.g., --filter=MyTest)'
    default: '--ci --parallel'
    required: false
  continue-on-error:
    description: 'Whether to continue on error'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        coverage: xdebug

    - name: Show PHP & Composer versions
      run: |
        php -v
        composer --version

    - name: Install Composer dependencies (with cache)
      uses: ramsey/composer-install@v3
      with:
        working-directory: ${{ inputs.working-directory }}
        composer-options: ${{ inputs.composer-options }}

    - name: Show Pest version
      run: vendor/bin/pest --version

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Prepare SQLite database & env
      run: |
        mkdir -p database
        touch database/database.sqlite
        cp .env.example .env
        php artisan key:generate --force

    - name: Run migrations
      run: php artisan migrate --force

    - name: Clear caches (prep)
      run: |
        php artisan config:clear
        php artisan cache:clear

    - name: Run Pest tests
      continue-on-error: ${{ inputs.continue-on-error }}
      run: vendor/bin/pest ${{ inputs.pest-args }}
